### ISSUE TITLE
Humidity returning value of 0

### ISSUE THREAD

**Issue by italicus-web** [cmur2/python-bme280#35]
Hello, 

I'm using an unbranded bme280 sensor, and everything seems to work fine but the humidity, which is always 0. 

Searching for possible solutions online I found a different directory which had the similar issue: https://github.com/rm-hull/bme280/issues/2

Could it be that the same problem is present also here?

Best

**Comment by cmur2** [comment]
Hi, thanks for bringing this up! I will have a look and come back to you :+1:

**Comment by cmur2** [comment]
I had a look at the line https://github.com/cmur2/python-bme280/blob/master/bme280/bme280.py#L207 that was discussed in https://github.com/rm-hull/bme280/issues/2 and I don't think the same problem is present here. If you still experience this error, there must be something else broken.

**Comment by italicus-web** [comment]
Thank you for looking into this. The error is still present in my sensor. 
Is there a way to see if the humidity sensor is giving a signal but this is not being decoded well, or if it is busted?

**Comment by cmur2** [comment]
There is probably a way but it also depends a bit on how much effort you are willing to take, it might be some back and forth since only you own the sensor :)

While this library does not provide out-of-the-box debug functionality I now created a fork of the code for you with debug statements to the terminal. You can find it at https://github.com/cmur2/python-bme280/tree/debug-issue-35
The most interesting printed value for your question "if the humidity sensor is giving a signal" will be in line https://github.com/cmur2/python-bme280/blob/debug-issue-35/bme280/bme280.py#L144

You should be able to run the code from https://github.com/cmur2/python-bme280/tree/debug-issue-35 in place of what you are currently using, make sure you can see the terminal output and then please provide the output back here so I can have a look - that would be great for narrowing the error :+1:

**Comment by italicus-web** [comment]
so I just run the demo.py file, and I think my sensor is not recording humidity altogether, so it was a hardware issue, nothing wrong with the code. 

digH0: 0
digH1: 0
digH2: 0
digH3: 0
digH4: 0
digH5: 0
humidity_raw: 0
var_H: 0.0

Thank you so much for providing the debugging option, hopefully it will be handy for others too.

**Comment by cmur2** [comment]
Ah, that looks like a limitation of the unbranded sensor's hardware (provided that e.g. the temperate_raw and pressure_raw output showed plausible values). I will think about a more structured debugging option for the future, thanks.
